config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  resources :sessions, only: [:new, :create, :destroy]
  resources :pictures do
    collection do
      post :confirm
    end
  end
  resources :users, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :image, presence: true
  validates :content, presence: true, length: { maximum: 60000 }
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def authenticate_user
    unless logged_in?
      if @current_user == nil
        flash[:notice] = t('notice.login_needed')
        redirect_to new_session_path
      end
    end
  end

  protect_from_forgery with: :exception
  include SessionsHelper
  
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = current_user.pictures.build(picture_params)
    if params[:back]
      render :new
    else
      respond_to do |format|
        if @picture.save
          format.html { redirect_to @picture }
          format.json { render :show, status: :created, location: @picture }
        else
          format.html { render :new }
          format.json { render json: @picture.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url }
      format.json { head :no_content }
    end
  end
  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end

private
  # Use callbacks to share common setup or constraints between actions.
def set_picture
  @picture = Picture.find(params[:id])
end

  # Only allow a list of trusted parameters through.
def picture_params
  params.require(:picture).permit(:image, :image_cache, :content)
end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
  
end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

private
def user_params
  params.require(:user).permit(:name, :email, :password,
                               :password_confirmation)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Face</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <header class="header clearfix">
        <div class="square">
          <%= link_to "F", root_path %>
        </div>
        <nav>
          <ul class="top_menu clearfix">
            <% if logged_in? %>
              <li><%= link_to current_user.name, user_path(current_user.id) %></li>
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "NewPicture", new_picture_path %></li>
              <li><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign up", new_user_path %></li>
              <li><%= link_to "Login", new_session_path %></li>
            <% end %>
          </ul>
        </nav>
      </header>
      <div class="content_box">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key}") %>
        <% end %>
        <%= yield %>
      </div>
    <footer>
      <p>Facebook © 2020</p>
    </footer>
    </div>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true, url:choose_new_or_edit) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
    <%= form.file_field :image unless @picture.image && @picture.image.url %>
    <%= form.hidden_field :image_cache %>
  </div><br>
  <div class="field">
    <div class="form-group">
      <%= form.label :content %>
      <%= form.text_area :content, class:"form-control", placeholder:current_user.name+"さん、その気持ち、シェアしよう" %>
    </div>
  </div><br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<h1>確認画面</h1>
<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
  <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %><br>
  <%= @picture.content %><br><br>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <%= form.submit "投稿する", class:"btn btn-info" %>
<% end %>
<br>
<%= form_with(model:@picture, url:new_picture_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <%= form.submit "戻る", name: "back", class:"btn btn-light" %>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pictures</h1>
  <% @pictures.each do |picture| %>
    <div class="panel panel-default"">
      <div class="panel-body">
        <%= picture.user.name %><br>
        <%= image_tag picture.image.url %><br>
        <%= picture.content %><br>
        <%= link_to 'Show', picture %>
        <%= link_to 'Edit', edit_picture_path(picture) %>
        <%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
  <% end %>

<br>

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag @picture.image.url %>
</p>

<p>
  <strong>Content:</strong>
  <%= @picture.content %>
</p>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>

app/views/top/index.html.erb
  <%= link_to 'New Picture', new_picture_path %><br>
  <%= link_to 'Index', pictures_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class:"form-control", placeholder:"氏名" %>
</div>
<div class="form-group">
  <%= f.label :email %>
  <%= f.email_field :email, class:"form-control", placeholder:"メールアドレス" %>
</div>
<div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, class:"form-control", placeholder:"パスワード" %>
</div>
<div class="form-group">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class:"form-control", placeholder:"パスワードの確認" %>
</div>
  <%= f.submit "Create my account", class:"btn btn-success" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス: <%= @user.email %></p>